###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "firstname": "daniel",
  "lastname": "fernando",
  "email": "xds@gmail.com",
  "password": "Franyoko10"
}


###
POST  http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "xkevinym@gmail.com",
  "password": "Franyoko10"
}
