GET http://localhost:8080/api/register
Content-Type: application/json

[
    {
        "firstName": "John",
        "lastName": "Doe",
        "email": "stevenvictoria.27@gmail.com",
        "password": "1234"
    }
]
